language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests

script:
  - py.test --cov gls_connector  --cov-report term gls_connector -x

after_success:
  - codecov

deploy:
  provider: pypi
  user: pipo
  password:
    secure: nUeXd2stka2YIo78KboT7y8XBITWdqf4kQgqHJZP/0b+ndWR7vsBPYka9aliheHz804IOQqdQmyPSTHNYCb045mQAF5m3MqYXxLrh4bwXwwP381TjAwK+bgk6HIggibbSckj4ZfdTO7GFTFN71ha0Tw6yLM6xFnMyzo6L/g2vvTWXGGR1bZKCKLptOE4qcjhhMpJmDORLctZcsekj/cn9lV+H4q74l3ea3Yd1dJu7+V/dQ/LkNrXoOMWBNiiTSwaCiSkEOuLSvcEmkkPLp3faXC7nnIkevk3W2FbBCPyp9Gq/WHR3BzF5hyWIHjrPF9al0glOOwoWgolpYUR67MHR80vG2mw5fdUDtNFeIizZUeaQvx88W9e0lj3SowO3ktaQU/74xj5R+9SJFsVfimw2jPTah0ZzNMdOdzGysYgTJQctEoutyjyaE+2lcqonL5hOeXaYZ8XA2FjBVnG2dd2A/Fg92IxUdpAhZrYj08Rh8t2Ni55t9QfqCByr4kEc/Rnx4CK2WBzYsK8gxKh2RE1o4nz7Ldo5SxvDegfgsYh1u7+dTUekTN73CsPX+4EnJhnVmJ3NTFmyYJE1cr+YQPTUZdxaCCAEDf24PNvkRo6duEw7D0D1vVoU65SSYcpCu9jIJNDAmGkS67QdfBxopXhs/Qwq7CpIhjHWpJWvBxdr9s=
  on:
    tags: true
  distributions: bdist_wheel
  skip_existing: true
